export const USER_ACTION_TYPES = {
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
    USER_SIGNED_IN_SUCCESS: 'user/USER_SIGNED_IN_SUCCESS',
    USER_SIGNED_IN_FAILED: 'user/USER_SIGNED_IN_FAILED',
    GOOGLE_SIGN_IN_START: 'user/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'user/EMAIL_SIGN_IN_START',
    USER_SIGN_UP_START: 'user/USER_SIGN_UP_START',
    USER_SIGNED_UP_SUCCESS: 'user/USER_SIGNED_UP_SUCCESS',
    USER_SIGNED_UP_FAILED: 'user/USER_SIGNED_UP_FAILED',
    USER_SIGN_OUT_START: 'user/USER_SIGN_OUT_START',
    USER_SIGN_OUT_SUCCESS: 'user/USER_SIGN_OUT_SUCCESS',
    USER_SIGN_OUT_FAILED: 'user/USER_SIGN_OUT_FAILED',
};